TGUI update(?)

diff --git a/tgui/bin/tgui b/tgui/bin/tgui
--- a/tgui/bin/tgui
+++ b/tgui/bin/tgui
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 ## Copyright (c) 2020 Aleksej Komarov
 ## SPDX-License-Identifier: MIT
 
@@ -26,18 +26,9 @@ fi
 base_dir="$(dirname "$(tgui-realpath "${0}")")/.."
 base_dir="$(tgui-realpath "${base_dir}")"
 
-## Make use of nvm if it exists
-if [[ -e "${HOME}/.nvm/nvm.sh" ]]; then
-  source "${HOME}/.nvm/nvm.sh"
-fi
-
 ## Fall back to running Yarn from the repo
 if ! hash yarn 2>/dev/null; then
-  yarn_releases=("${base_dir}"/.yarn/releases/yarn-*.cjs)
-  yarn_release="${yarn_releases[0]}"
-  yarn() {
-    node "${yarn_release}" "${@}"
-  }
+  alias yarn="node '${base_dir}/.yarn/releases/yarn-berry.js'"
 fi
 
 
@@ -63,17 +54,10 @@ task-dev-server() {
 }
 
 ## Run a linter through all packages
-task-lint() {
+task-eslint() {
   cd "${base_dir}"
-  yarn run tsc
-  echo "tgui: type check passed"
-  yarn run eslint packages --ext .js,.cjs,.ts,.tsx "${@}"
+  yarn run eslint packages "${@}"
   echo "tgui: eslint check passed"
-}
-
-task-test() {
-  cd "${base_dir}"
-  yarn run jest
 }
 
 ## Mr. Proper
@@ -82,20 +66,29 @@ task-clean() {
   ## Build artifacts
   rm -rf public/.tmp
   rm -f public/*.map
-  rm -f public/*.chunk.*
-  rm -f public/*.bundle.*
   rm -f public/*.hot-update.*
   ## Yarn artifacts
   rm -rf .yarn/cache
   rm -rf .yarn/unplugged
-  rm -rf .yarn/webpack
-  rm -f .yarn/build-state.yml
-  rm -f .yarn/install-state.gz
-  rm -f .yarn/install-target
+  rm -rf .yarn/build-state.yml
+  rm -rf .yarn/install-state.gz
   rm -f .pnp.js
   ## NPM artifacts
   rm -rf **/node_modules
   rm -f **/package-lock.json
+}
+
+## Validates current build against the build stored in git
+task-validate-build() {
+  cd "${base_dir}"
+  local diff
+  diff="$(git diff public/*)"
+  if [[ -n ${diff} ]]; then
+    echo "Error: our build differs from the build committed into git."
+    echo "Please rebuild tgui."
+    exit 1
+  fi
+  echo "tgui: build is ok"
 }
 
 ## Installs merge drivers and git hooks
@@ -140,6 +133,16 @@ if [[ ${1} == "--install-git-hooks" ]]; then
   exit 0
 fi
 
+## Continuous integration scenario
+if [[ ${1} == "--ci" ]]; then
+  task-clean
+  task-install
+  task-eslint
+  task-webpack --mode=production
+  task-validate-build
+  exit 0
+fi
+
 if [[ ${1} == "--clean" ]]; then
   task-clean
   exit 0
@@ -155,28 +158,21 @@ fi
 if [[ ${1} == '--lint' ]]; then
   shift 1
   task-install
-  task-lint "${@}"
+  task-eslint "${@}"
   exit 0
 fi
 
 if [[ ${1} == '--lint-harder' ]]; then
   shift 1
   task-install
-  task-lint -c .eslintrc-harder.yml "${@}"
+  task-eslint -c .eslintrc-harder.yml "${@}"
   exit 0
 fi
 
 if [[ ${1} == '--fix' ]]; then
   shift 1
   task-install
-  task-lint --fix "${@}"
-  exit 0
-fi
-
-if [[ ${1} == '--test' ]]; then
-  shift 1
-  task-install
-  task-test "${@}"
+  task-eslint --fix "${@}"
   exit 0
 fi
 
@@ -188,16 +184,9 @@ if [[ ${1} == '--analyze' ]]; then
 fi
 
 ## Make a production webpack build
-if [[ ${1} == '--build' ]]; then
-  task-install
-  task-webpack --mode=production
-  exit 0
-fi
-
-## Make a production webpack build + Run eslint
 if [[ -z ${1} ]]; then
   task-install
-  task-lint --fix
+  task-eslint
   task-webpack --mode=production
   exit 0
 fi
